### ISSUE TITLE
HelmRelease is not created

### ISSUE THREAD

**Issue by moikot** [fluxcd/toolkit#208]
I'm trying to use the latest version of the toolkit and create some services using HelmRelease. I created the following resources in my repository:

```YAML
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: stable-helm-repo
  namespace: gitops-system
spec:
  interval: 1h
  url: https://kubernetes-charts.storage.googleapis.com
```

```YAML
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: '7.1.x'
      sourceRef:
        kind: HelmRepository
        name: stable-helm-repo
        namespace: gitops-system
      interval: 1m
```

While I see that HelmRepository resource is correctly created during the synchronization process, but HelmRelease is missing although the source-controller doesn't report any error.
