### ISSUE TITLE
HelmRepository stuck on "reconciliation in progress"

### ISSUE THREAD

**Issue by sseneca** [fluxcd/toolkit#245]
I tried adding the following:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: gitops-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
```

Nothing interesting from the logs:

```json
{
  "level": "info",
  "ts": "2020-09-19T15:44:21.605Z",
  "logger": "controllers.HelmRepository",
  "msg": "Reconciliation finished in 164.626884ms, next run in 1m0s",
  "controller": "helmrepository",
  "request": "gitops-system/ingress-nginx"
}
```

But when I do `kubectl get helmrepository`:

```
NAME            URL                                                READY     STATUS                                             AGE
ingress-nginx   https://kubernetes.github.io/ingress-nginx         Unknown   reconciliation in progress                         4m35s
nextcloud       https://nextcloud.github.io/helm/                  True      Fetched revision: 2020-08-26T16:22:56.644290771Z   106m
bitnami         https://charts.bitnami.com/bitnami                 True      Fetched revision: 2020-09-19T14:51:05.445858887Z   106m
stable          https://kubernetes-charts.storage.googleapis.com   True      Fetched revision: 2020-09-19T15:28:46.2113521Z     6m38s
```

It's stuck on `Unknown` with `reconciliation in progress`.

If I run `gotk reconcile source helm ingress-nginx https://kubernetes.github.io/ingress-nginx`:

```
► annotating source ingress-nginx in gitops-system namespace
✔ source annotated
◎ waiting for reconciliation
✗ context deadline exceeded
```

This happens with any new repositories I try to add. Only the three currently with "Ready" as `True` are functional.

**Comment by sseneca** [comment]
Is there a limit for 3 Helm repositories? I removed the `nextcloud` repo and the `ingress-nginx` repo started to work (though then the `HelmRelease` got stuck and gave me a "✗ context deadline exceeded" instead).

**Comment by hiddeco** [comment]
Using both a fresh build from `master` for the source-controller and the latest release (`v0.0.16`), I was unable to reproduce the issue as you describe it.

```yaml
# repositories.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 1m
  url: https://nextcloud.github.io/helm/
---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: stable
spec:
  interval: 1m
  url: https://kubernetes-charts.storage.googleapis.com
```

```console
$ kubectl apply -f repositories.yaml
helmrepository.source.toolkit.fluxcd.io/ingress-nginx created
helmrepository.source.toolkit.fluxcd.io/nextcloud created
helmrepository.source.toolkit.fluxcd.io/bitnami created
helmrepository.source.toolkit.fluxcd.io/stable created
$ kubectl get helmrepositories
NAME            URL                                                READY   STATUS                                             AGE
bitnami         https://charts.bitnami.com/bitnami                 True    Fetched revision: 2020-09-21T07:55:56.784876437Z   17s
ingress-nginx   https://kubernetes.github.io/ingress-nginx         True    Fetched revision: 2020-04-26T21:05:21.59370903Z    17s
nextcloud       https://nextcloud.github.io/helm/                  True    Fetched revision: 2020-08-26T16:22:56.644290771Z   17s
stable          https://kubernetes-charts.storage.googleapis.com   True    Fetched revision: 2020-09-21T07:03:24.331341492Z   17s
$ gotk reconcile source helm ingress-nginx
► annotating source ingress-nginx in source-system namespace
✔ source annotated
◎ waiting for reconciliation
✔ helm reconciliation completed
✔ fetched revision 2020-04-26T21:05:21.59370903Z
```

---

Given this, can you please check if the `source-controller` deployment in the `gitops-system` namespace hits any resource limits (and gets `OOMKilled`), or if the `/data` path it writes to runs out of storage?

**Comment by sseneca** [comment]
Here are the logs of the `source-controller`: https://ghostbin.co/paste/k2o5g

I don't see anything about it hitting resource limits or running out of storage.

Not sure if it's relevant but it shows reconciliation finishing for all the Helm repos but in reality only `bitnami` and `stable` showed up with "Ready" as `True`

**Comment by hiddeco** [comment]
Can you please share the output of `kubectl describe helmrepository`?

**Comment by sseneca** [comment]
Sure: https://ghostbin.co/paste/d35yr

**Comment by hiddeco** [comment]
Can you simply try to kick the `source-controller` pod?

**Comment by sseneca** [comment]
Yep, deleting the `source-controller` pod seems to work. All the `helmrepositories` became Ready after it restarted.

I added a couple more Helm repos and the same thing happened; deleting the pod fixed that as well.

**Comment by stefanprodan** [comment]
@sseneca what Kubernetes distribution are you using?

**Comment by sseneca** [comment]
@stefanprodan  [k3s.io](https://k3s.io)

**Comment by hiddeco** [comment]
@sseneca can you re-trigger this "deadlock" again and share the following:

- logs from the moment the Helm repositories are added till they end up in a deadlock state
- `kubectl describe` of the resources that are locked on `Ready==False`

**Comment by sseneca** [comment]
I added the vmware-tanzu repo (https://vmware-tanzu.github.io/helm-charts/).

The `source-controller` logs:

```json
{
  "level": "info",
  "ts": "2020-09-22T10:44:01.050Z",
  "logger": "controllers.GitRepository",
  "msg": "Reconciliation finished in 1.368930928s, next run in 1m0s",
  "controller": "gitrepository",
  "request": "gitops-system/gitops-system"
}
{
  "level": "info",
  "ts": "2020-09-22T10:44:02.300Z",
  "logger": "controllers.HelmRepository",
  "msg": "Reconciliation finished in 545.068806ms, next run in 1m0s",
  "controller": "helmrepository",
  "request": "gitops-system/vmware-tanzu"
}
{
  "level": "info",
  "ts": "2020-09-22T10:44:02.370Z",
  "logger": "controllers.HelmRepository",
  "msg": "Reconciliation finished in 70.135101ms, next run in 1m0s",
  "controller": "helmrepository",
  "request": "gitops-system/vmware-tanzu"
}
{
  "level": "info",
  "ts": "2020-09-22T10:44:02.529Z",
  "logger": "controllers.HelmRepository",
  "msg": "Reconciliation finished in 79.235983ms, next run in 1m0s",
  "controller": "helmrepository",
  "request": "gitops-system/vmware-tanzu"
}
```

`kubectl describe`:

```yaml
Name:         vmware-tanzu
Namespace:    gitops-system
Labels:       kustomization/name=gitops-system-gitops-system
              kustomization/revision=faef7c497d87e267b3f9e9d95d8232d5310cab3f
Annotations:  <none>
API Version:  source.toolkit.fluxcd.io/v1alpha1
Kind:         HelmRepository
Metadata:
  Creation Timestamp:  2020-09-22T10:44:01Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  3
  Managed Fields:
    API Version:  source.toolkit.fluxcd.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:kustomization/name:
          f:kustomization/revision:
      f:spec:
        .:
        f:url:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2020-09-22T10:44:02Z
    API Version:  source.toolkit.fluxcd.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
      f:spec:
        f:interval:
      f:status:
        .:
        f:artifact:
          .:
          f:checksum:
          f:lastUpdateTime:
          f:path:
          f:revision:
          f:url:
        f:conditions:
        f:observedGeneration:
    Manager:         source-controller
    Operation:       Update
    Time:            2020-09-22T10:44:02Z
  Resource Version:  95170
  Self Link:         /apis/source.toolkit.fluxcd.io/v1alpha1/namespaces/gitops-system/helmrepositories/vmware-tanzu
  UID:               ac3d650d-2045-4ffd-88f9-72f7ea4c47c8
Spec:
  Interval:  1m
  URL:       https://vmware-tanzu.github.io/helm-charts/
Status:
  Artifact:
    Checksum:          7b54b0c5a1fe13f666cffcfe9420b0280a8e7e75
    Last Update Time:  2020-09-22T10:44:02Z
    Path:              helmrepository/gitops-system/vmware-tanzu/index-2019-12-18T18:07:47.212339875Z.yaml
    Revision:          2019-12-18T18:07:47.212339875Z
    URL:               http://source-controller.gitops-system/helmrepository/gitops-system/vmware-tanzu/index-2019-12-18T18:07:47.212339875Z.yaml
  Conditions:
    Last Transition Time:  2020-09-22T10:44:02Z
    Message:               reconciliation in progress
    Reason:                Progressing
    Status:                Unknown
    Type:                  Ready
  Observed Generation:     3
Events:
  Type    Reason  Age   From               Message
  ----    ------  ----  ----               -------
  Normal  info    38s   source-controller  Fetched revision: 2019-12-18T18:07:47.212339875Z
```

by the way, it gets stuck in `Ready` =  `Unknown`, I haven't seen it get to `Ready` = `False`.
