### ISSUE TITLE
helm release getting deployed into gotk-system namespace

### ISSUE THREAD

**Issue by yawboateng** [fluxcd/toolkit#314]
I have a helmrelease:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev
  namespace: dev
spec:
  interval: 2m
  timeout: 25m
  chart:
    spec:
      chart: fusion
      version: '5.2.x'
      sourceRef:
        kind: HelmRepository
        name: lucidworks
        namespace: gotk-system
      interval: 1m
```
after pushing changes into the git repo, i ran: `kubectl gotk reconcile` (which failed)
```
 bernard git:(master) ✗ kubectl gotk reconcile helmrelease dev --namespace dev
► annotating HelmRelease dev in dev namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✔ HelmRelease reconciliation completed
✗ HelmRelease reconciliation failed
```
However, everything seems to be going into the gotk-system namespace instead of the dev defined in the helmrelase
```
➜  bernard git:(master) ✗ k -n gotk-system get pods                             
NAME                                        READY   STATUS     RESTARTS   AGE
dev-admin-ui-6c8c779c49-rcpqg               1/1     Running    0          5m3s
dev-api-gateway-8cf8c5db9-wlnd6             0/1     Init:0/2   0          5m3s
dev-api-gateway-8cf8c5db9-zkhkr             0/1     Init:0/2   0          5m4s
dev-auth-ui-75f75d786c-fx8xx                1/1     Running    0          5m3s
dev-classic-rest-service-0                  0/1     Init:0/2   2          5m2s
dev-devops-ui-7c9c7c5687-26l2w              1/1     Running    0          5m3s
helm-controller-844b4d6486-kfmrz            1/1     Running    0          5d4h
kustomize-controller-74f97d8ccb-qvxwn       1/1     Running    0          5d4h
notification-controller-6cb447958f-nkqwt    1/1     Running    0          5d4h
source-controller-856f444b5c-f5lkd          1/1     Running    0          5d4h
```
not much info in the logs :(
